/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {


}
